CREATE TABLE IF NOT EXISTS PRODUCT(PRODUCTID INTEGER PRIMARY KEY AUTO_INCREMENT,
                    PRODUCTNAME VARCHAR(255),
                    PRICE DOUBLE); 

CREATE TABLE IF NOT EXISTS REVIEW(REVIEWID INTEGER PRIMARY KEY AUTO_INCREMENT,
                    REVIEWCONTENT VARCHAR(255),
                    RATING INTEGER,
                    PRODUCTID INTEGER,FOREIGN KEY(PRODUCTID)REFERENCES PRODUCT(PRODUCTID));